databases:
  - name: shopware
    databaseName: shopware
    user: shopware



services:
  - type: web
    name: shopware
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn shopware.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shopware
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
